=== neikila/ImitationModelling/res/model.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="model">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="deadline" type="xsd:double"/>
        <xsd:element name="stopGenerating" type="xsd:double"/>

        <xsd:element name="events">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="RequestIncome" type="productEvent"/>
              <xsd:element name="RequestRequest" type="productEvent"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="productEvent">
    <xsd:sequence>
      <xsd:element name="delta" type="positiveDouble"/>
      <xsd:element name="amount" type="positiveDouble"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="positiveDouble">
    <xsd:restriction base="xsd:double">
      <xsd:minExclusive value="0" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== neikila/ImitationModelling/res/Model.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="storage.xsl"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model.xsd">
  <deadline>150.0</deadline>
  <stopGenerating>100.0</stopGenerating>
  <events>
    <RequestIncome>
      <delta>50</delta>
      <amount>10</amount>
    </RequestIncome>
    <RequestRequest>
      <delta>50</delta>
      <amount>10</amount>
    </RequestRequest>
  </events>
</model>
