=== neikila/ImitationModelling/res/storage.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">  
  <xsd:element name="storage">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="bounds" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="barriers" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="bounds" type="polygon" />
  <xsd:element name="barriers">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="barrier" type="polygon" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="point">
    <xsd:complexType>
      <xsd:attribute name="x" type="xsd:double"/>
      <xsd:attribute name="y" type="xsd:double"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="polygon">
    <xsd:sequence>
      <xsd:element ref="point" minOccurs="3" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== neikila/ImitationModelling/res/Storage.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="storage.xsl"?>
<storage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storage.xsd">
  <bounds>
    <point x="0" y="0"/>
    <point x="120" y="0"/>
    <point x="120" y="120"/>
    <point x="0" y="120"/>
  </bounds>
  <barriers>
    <barrier>
      <point x="35" y="35"/>
      <point x="45" y="35"/>
      <point x="45" y="45"/>
      <point x="35" y="45"/>
    </barrier>
    <barrier>
      <point x="75" y="75"/>
      <point x="85" y="75"/>
      <point x="85" y="85"/>
      <point x="75" y="85"/>
    </barrier>
    <barrier>
      <point x="75" y="75"/>
      <point x="85" y="75"/>
      <point x="85" y="85"/>
      <point x="75" y="85"/>
    </barrier>
    <barrier>
      <point x="35" y="35"/>
      <point x="45" y="35"/>
      <point x="45" y="45"/>
      <point x="35" y="45"/>
    </barrier>
  </barriers>
</storage>
